FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy full application code
COPY . .

# Environment variables at build time for Next.js static bundling
ARG NEXT_PUBLIC_API_URL=http://localhost:11111
ARG NEXT_PUBLIC_SOCKET_ENDPOINT=http://localhost:10085/v1/notifications/ws
ARG NEXT_PUBLIC_GIPHY_API_KEY=s3XNxnnBvsE7WlQWDl48XSfs7pRI8db4
ARG NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyDkdLugBgnKR-qblnKfGB1lhmaYIOeItLU
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=pocpoc-498009.firebaseapp.com
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=pocpoc-498009
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=pocpoc-498009.firebasestorage.app
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1041761445609
ARG NEXT_PUBLIC_FIREBASE_APP_ID=1:1041761445609:web:5723e585989001b06b7278
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-15FZZEQH65
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY=BKbRO4nYdzFR4JeYR3Ibh0vrAjzGWXCQaGxkfejFQzCe0eQs4POvKBF_VC1iIqQtJ6vmouzalIxQXFQLOXJ9atw
ARG NEXT_PUBLIC_CAPTCHA_SITE_KEY=0x4AAAAAAECyZYgQWJNisZQ4

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_SOCKET_ENDPOINT=${NEXT_PUBLIC_SOCKET_ENDPOINT}
ENV NEXT_PUBLIC_GIPHY_API_KEY=${NEXT_PUBLIC_GIPHY_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
ENV NEXT_PUBLIC_CAPTCHA_SITE_KEY=${NEXT_PUBLIC_CAPTCHA_SITE_KEY}
ENV NODE_ENV=production

RUN npm run build

# Stage 2: Lightweight Production Runtime
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=10000

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/messages ./messages

EXPOSE 10000

CMD ["npm", "run", "start", "--", "-p", "10000"]
